<template>
  <div class="cms-page">
    <!-- Loading State -->
    <div v-if="pending" class="container py-5 text-center">
      <div class="spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>

    <!-- CMS Content (if available) -->
    <div v-else-if="cmsPage" class="cms-loaded">
      <PageHero
        :title="cmsPage.title"
        :subtitle="cmsPage.subtitle || ''"
        variant="gradient"
      />
      <div class="container py-5">
        <div class="cms-content" v-html="cmsPage.content"></div>
        <div v-if="cmsPage.last_updated" class="text-muted text-center mt-5 small">
          Last Updated: {{ formatDate(cmsPage.last_updated) }}
        </div>
      </div>
    </div>

    <!-- Static Fallback Content -->
    <div v-else class="legal-page">
      <div class="container">
        <div class="legal-content">
          <h1>User Agreement - Terms and Conditions</h1>
          <p class="last-updated">Last Updated: January 7, 2026</p>

        <div class="important-notice">
          <p><strong>READ THIS DOCUMENT CAREFULLY BEFORE USING THIS SITE. IT SETS FORTH THE LEGALLY BINDING TERMS AND CONDITIONS FOR YOUR USE OF THIS SITE, AND CONTAINS IMPORTANT INFORMATION ABOUT YOUR RIGHTS AND OBLIGATIONS.</strong></p>
          <p>This document is an electronic record generated by a computer system and does not require any physical or digital signatures.</p>
        </div>

        <section>
          <h2>1. Acknowledgement of Agreement</h2>
          <p>
            This is an agreement between you ("User," "you," or "your") and Rishipath ("Rishipath," "we," or "our") that governs your use of the services offered through our website <strong>www.rishipath.com</strong> ("Website"), mobile app, services, tools, or any other medium using which Rishipath may provide services (collectively "Platforms").
          </p>
          <p>
            When you access or use any of the Platforms, you agree to be bound by these Terms and Conditions (including the linked information herein) and represent that you agree to comply with these terms and conditions (the "User Agreement"). This User Agreement is deemed effective upon your use of any of the Platforms, which signifies your continuing acceptance of these terms and conditions.
          </p>
          <p>
            <strong>If you do not agree to be bound by this User Agreement, please do not access, register with, or use this Platform.</strong>
          </p>
        </section>

        <section>
          <h2>2. Modifications</h2>
          <p>
            Rishipath retains the authority to revise, alter, append, or eliminate sections of these Terms and Conditions without advance notice. Adjustments will become active upon being published on the website, without any supplementary notification. We advise you to frequently review these Terms and Conditions for any updates. Your continued use of the website after the publication of changes to the Terms and Conditions signifies your acceptance of those modifications.
          </p>
        </section>

        <section>
          <h2>3. Usage of Our Materials</h2>
          <p>
            We use a diverse range of information, text, photographs, designs, graphics, images, sound and video recordings, content, advertisements, and other materials and effects (collectively "Materials") for your usage on the Platforms. We provide the Material through the Platforms <strong>FOR YOUR PERSONAL AND NON-COMMERCIAL USE ONLY</strong>.
          </p>
          <p>
            We assume no responsibility for any manner of damages, losses, or actions that arise either directly or indirectly as a consequence of accessing and/or utilizing the content within the Platforms. This encompasses, without limitation, decisions predicated on the content found within the Platforms that lead to but are not limited to any form of data loss, reduction in revenue, profits, property, infection by viruses, and other similar outcomes.
          </p>
          <p>
            As a result, you have the permission to look at, use, copy, and share the content you find on the Platforms, but only for your own personal and non-commercial purposes. However, using methods like data mining, scraping, or automated queries to extract information from Rishipath is strictly not allowed. You're also not allowed to create a collection of listings that competes with Rishipath's services using the content from the Platforms. Sending unsolicited commercial emails using the content from the Platforms is also not allowed.
          </p>
          <p>
            Unless explicitly stated in this section, you don't have the right to use any copyrights, trademarks, patents, or other intellectual property related to the content, products, services, or technologies mentioned. All these rights are owned by Rishipath, its subsidiaries, parent companies, or other third-party owners.
          </p>
        </section>

        <section>
          <h2>4. Registration</h2>
          <p>
            In order to access specific services provided by the Platforms, we may require that you register with us by creating an account with us or provide personal information to complete the creation of the account. Rishipath shall retain the discretionary right to invalidate usernames and/or passwords at any time, without prior notice, without incurring any liability or responsibility for resulting losses.
          </p>
          <p>
            It is incumbent upon you to ensure the accuracy and completeness of the details you furnish to us at all times. You bear the obligation to promptly and accurately update your account information in real-time through online access to your account. For any particulars that cannot be amended via direct access to your account on the Site, you are required to notify us through our designated customer service communication channels, whereby we will assist you in effecting these modifications.
          </p>
          <p>
            By accessing and utilizing the Site and its associated services, you hereby assume full responsibility for maintaining the confidentiality of your user identification, password, account particulars, and any other related private information. You explicitly agree to acknowledge and accept this responsibility, ensuring the secure maintenance of your account and its associated details at all times, and to undertake all requisite measures to forestall any form of account misuse.
          </p>
          <p>
            In the event that you have reasonable cause to suspect that your password has been disclosed to any third party or is being, or is likely to be, employed in an unauthorized manner, it is incumbent upon you to promptly inform us of such circumstances.
          </p>
          <p>
            You hereby affirmatively consent and acknowledge that any utilization of the Site, its offered services, and any access to private information, data, or communications facilitated through your account and password shall be construed as either executed by you or duly sanctioned by you, as the situation warrants.
          </p>
          <p>
            We retain the authority to deny access to the Site, terminate accounts, or modify or remove content without prior notification to you. At our sole and absolute discretion, we reserve the right to request updates to your Personal Data or to promptly invalidate the account or related particulars, without providing any explanation or advance notice. We shall not be held liable or accountable for any losses sustained by you, caused by you, or arising directly or indirectly from such a request or invalidation.
          </p>
        </section>

        <section>
          <h2>5. Privacy</h2>
          <p>
            Please carefully review our <NuxtLink to="/privacy-policy">Privacy Policy</NuxtLink>, as it holds authority over your interactions with the Site. Any personal information or data you furnish to us or generate through your utilization of the Site will be subject to stringent confidentiality measures, in accordance with the terms of the Privacy Policy and pertinent legal statutes.
          </p>
          <p>
            Should you dissent from the manner in which your information is intended to be transferred or used, as stipulated within the Privacy Policy, we respectfully advise refraining from using the Site.
          </p>
          <p>
            You shall refrain from transmitting confidential or proprietary information to us. Notwithstanding any personally identifiable information that we have agreed to treat as confidential, in accordance with the provisions of our Privacy Policy, any materials—such as feedback, data, responses, queries, comments, suggestions, ideas, or similar content—that you convey to us shall be considered as non-confidential and non-proprietary.
          </p>
          <p>
            We explicitly disclaim any obligation to safeguard confidential or proprietary information, excluding personally identifiable information, from disclosure. Consequently, we shall have the liberty to replicate, employ, and disseminate said information to third parties without encumbrance.
          </p>
        </section>

        <section>
          <h2>6. Availability of the Platforms</h2>
          <p>
            We are committed to making every effort to maintain a consistent and uninterrupted availability of the Site, free from errors. However, given the inherent characteristics of both the Internet and the Site, complete assurance of such continuity cannot be provided.
          </p>
          <p>
            Furthermore, there may be instances when your access to the Site is temporarily suspended or limited. This may occur to facilitate repairs, maintenance activities, or the introduction of new features or services. Such occurrences may take place without prior notice. Our aim is to minimize the frequency and duration of such temporary suspensions or restrictions.
          </p>
        </section>

        <section>
          <h2>7. User Access and License</h2>
          <p>
            The content provided on the Site is meant for informational purposes only. Details such as product representations, prices, availability, features, and other aspects presented on the Site are provided by Rishipath. We strive for accuracy but do not guarantee absolute precision. Opinions expressed on the Site belong to the individuals posting them and may not necessarily reflect our standpoint.
          </p>
          <p>
            Reproduction, duplication, sale, distribution, or exploitation of the Site or its components (including copyrighted material and trademarks) for commercial purposes necessitates our express written consent.
          </p>
          <p>
            By accessing the Site, you affirm your ability to enter legally binding agreements and confirm that you are either at least eighteen (18) years old or are using the Site under the guidance of a parent or legal guardian. We extend to you a non-transferable, non-exclusive, and revocable license in accordance with the stipulated Terms and Conditions.
          </p>
          <p>
            This license enables you to use the Site for the purpose of personal shopping, specifically for Ayurvedic products, wellness courses, educational content, and consultation services listed on the Site. However, engaging in commercial use or acting on behalf of a third party is strictly prohibited, except when expressly sanctioned by us in advance.
          </p>
          <p>
            If you are registering as a business entity, you assert that you have the authority to bind said entity to this User Agreement and that both you and the business entity will adhere to all applicable laws pertinent to online trading. It's important to note that registering multiple times as a member of the Site, whether as an individual or business entity, is prohibited.
          </p>
          <p>
            Any violation of these Terms and Conditions will result in the immediate and unilateral withdrawal of the license granted herein, without prior notice.
          </p>
        </section>

        <section>
          <h2>8. Restrictions and Compliance</h2>
          <p>
            You are solely responsible for the content of any transmissions you make to the Site or any transmissions you make to any mediums offered by Rishipath and any materials you add to the Site or add to any mediums offered by Rishipath.
          </p>
          <p>
            Failure to comply with these Terms and Conditions or any other guidelines and policies stated on the Site may lead to the cancellation of your account, services, orders, reviews, or any ongoing transactions. More severe cases could also result in legal action.
          </p>
          <p><strong>This encompasses activities, not limited to, such as:</strong></p>
          <ul>
            <li>Refusal to comply with the Terms and Conditions set forth herein or any supplementary guidelines and policies governing Site usage</li>
            <li>Uploading or distributing obscene, indecent, pornographic, profane, sexually explicit, threatening, or abusive content</li>
            <li>Impersonation of any individual or entity, or any attempt to falsely represent your affiliation with any individual or entity</li>
            <li>Using content that slanders, libels, defames, disparages, impersonates or otherwise violates the legal rights of any third party</li>
            <li>Using content that victimizes, harasses, degrades, or intimidates an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age or disability</li>
            <li>Infringing or violating the intellectual property rights (including copyright, patent and trademark rights), contract rights, trade secrets, privacy or publicity rights or any other rights of any third party</li>
            <li>Using content that contains software viruses or any other malicious code designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment</li>
            <li>Violating acceptable use policies, Internet standards, or applicable laws</li>
          </ul>
          <p>
            It is also clarified that, if there are any issues or claims due to your content, then Rishipath reserves the right to take appropriate legal action against you. Further, you shall indemnify and protect Rishipath against such claims or damages or any issues due to your content. Rishipath takes no responsibility and assumes no liability for any content posted by you or any third party on the Website or on any mediums of Rishipath.
          </p>
        </section>

        <section>
          <h2>9. User Submissions</h2>
          <p>
            Any material or information that you submit to the Website or provide to us, encompassing but not limited to queries, reviews, comments, and suggestions ("Submissions"), is subject to additional terms and conditions as mentioned herein.
          </p>
          <p>
            You are solely accountable for the Submissions you share with Rishipath through the Website or any other mediums provided by Rishipath. Rishipath doesn't endorse or adopt your Submissions as representative of their views.
          </p>
          <p>
            By transmitting any public Submissions to the Site, you grant an irrevocable, non-exclusive, worldwide, perpetual, unrestricted, royalty-free license (with the right to sub-license) to use, reproduce, distribute, publicly display, publicly perform, adapt, modify, edit, create derivative works from, incorporate into one or more compilations and reproduce and distribute such compilations, and otherwise exploit such Submissions, in all Platforms now known or later developed.
          </p>
          <p>
            You hereby waive and grant to Rishipath all rights including intellectual property rights and also "moral rights" in your Submissions, posted at Website through any mediums of Rishipath. Rishipath is free to use all your Submissions as per its requirements from time to time.
          </p>
          <p>
            You represent and warrant that you own or otherwise control all of the rights to the content that you post as Submissions; that the content is accurate; that use of the content you supply does not violate these Terms and will not cause injury to any person or entity. Also, Rishipath reserves the right to mask or unmask your identity in respect of your Submissions posted by you.
          </p>
          <p>
            Rishipath has the right, but not the obligation to monitor and edit or remove any content posted by you. Rishipath cannot review all Submissions made on and through any of the mediums of Rishipath. However, Rishipath reserves the right, but has no obligation, to monitor and edit, modify or delete any Submissions (or portions thereof) which Rishipath in its sole discretion deems inappropriate, offensive or contrary to any policy, or that violate these terms.
          </p>
          <p>
            If you want to manage, change, delete, or edit your information, we allow you to do so by contacting us through Rishipath Customer Service via Email at <strong>{{ brand.email }}</strong>.
          </p>
        </section>

        <section>
          <h2>10. Claims Against Objectionable Content</h2>
          <p>
            Given the extensive array of products and content on the Site, it is not feasible for us to be aware of all content displayed. Thus, we function on a "claim, review, and removal" basis.
          </p>
          <p>
            If you believe any content on the Site is illegal, offensive, deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libelous, obscene, pornographic, menacing, ethnically objectionable, disparaging, or otherwise detrimental to third parties, or pertains to money laundering, gambling, or any form of harm to minors, or impersonation, or threatens national unity, integrity, security, or relations with foreign States, or is objectionable or unlawful, or contains software viruses ("objectionable content"), kindly inform us promptly via email at <strong>{{ brand.email }}</strong>.
          </p>
          <p>
            To facilitate prompt action, provide your name, address, contact details, and comprehensive claim specifics, including the objectionable content's party name, instances of objection, and supporting evidence. Note that incomplete details render your claim invalid for legal purposes. We shall diligently investigate and endeavor to remove valid objectionable content within a reasonable period.
          </p>
        </section>

        <section>
          <h2>11. Scheduled Maintenance</h2>
          <p>
            Rishipath may, from time to time, require updating/upgrading/maintaining their Platform, which may lead to service downtime, and the User agrees to indemnify Rishipath from any claims/issues arising out of the same.
          </p>
          <p>
            Rishipath may launch, change, upgrade, impose conditions to, suspend, or stop any Services (or any features within the Services) without prior notice except that in case of a fee-based Service, such changes will not substantially adversely affect the ability of such Users to enjoy that Service.
          </p>
        </section>

        <section>
          <h2>12. Intellectual Property Rights</h2>
          <p>
            Rishipath's company names and logos, including but not limited to all related products and service names, design marks and slogans, are trademarks and service marks owned by and used under license from Rishipath or its wholly owned subsidiaries and may not be used in connection with any product or service that does not belong to us or in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits us.
          </p>
          <p>
            All other trademarks and service marks herein are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by us.
          </p>
          <p>
            All copies that you make of the Materials on any of the Platforms must bear any copyright, trademark or other proprietary notice located on the respective Platforms that pertains to the material being copied. You are not authorized to use any Rishipath name or mark in any advertising, publicity or in any other commercial manner without the prior written consent of Rishipath. Requests for authorization should be made to <strong>{{ brand.email }}</strong>.
          </p>
        </section>

        <section>
          <h2>13. Content Disclaimer</h2>
          <p>
            Rishipath communicates information provided and created by content partners, software developers, publishers, marketing agents, employees, users, and other third parties. While every attempt has been made to ascertain the authenticity of the content on the Platforms, Rishipath has no control over content, the accuracy of such content, integrity or quality of such content and the information on our pages, and material on the Platforms may include technical inaccuracies or typographical errors, and we make no guarantees, nor can we be responsible for any such information, including its authenticity, currency, content, quality, copyright compliance or legality, or any other intellectual property rights compliance, or any resulting loss or damage.
          </p>
          <p>
            Further, we are not liable for any kind of damages, losses or action arising directly or indirectly due to any content, including any errors or omissions in any content, access and/or use of the content on the Platforms or any of them including but not limited to content based decisions resulting in loss of data, revenue, profits, property, infection by viruses etc.
          </p>
        </section>

        <section>
          <h2>14. Products and Services</h2>
          <p>Our services include:</p>
          <ul>
            <li>Purchase of authentic Ayurvedic products and wellness items</li>
            <li>Enrollment in Ayurveda courses and wellness events</li>
            <li>Access to educational content including home remedies, yoga, meditation, and Ayurvedic recipes</li>
            <li>Consultation bookings with certified Ayurvedic practitioners</li>
            <li>Access to Ayurvedic glossary and knowledge resources</li>
          </ul>
          <p>
            All product descriptions, pricing, and availability are provided for informational purposes. We strive for accuracy but do not guarantee that all information is complete, reliable, current, or error-free. Products are subject to availability, and we reserve the right to limit quantities or refuse service.
          </p>
        </section>

        <section>
          <h2>15. Orders and Payment</h2>
          <ul>
            <li>All orders are subject to acceptance and product availability</li>
            <li>We reserve the right to refuse or cancel any order for any reason</li>
            <li>Payment must be completed before order processing begins</li>
            <li>Prices are subject to change without prior notice</li>
            <li>All transactions are processed securely through authorized payment gateways</li>
            <li>Shipping charges apply as per our <NuxtLink to="/shipping-policy">Shipping Policy</NuxtLink></li>
            <li>Returns and refunds are governed by our <NuxtLink to="/return-policy">Return Policy</NuxtLink></li>
          </ul>
        </section>

        <section>
          <h2>16. Indemnification</h2>
          <p>
            You agree to indemnify and hold us and (as applicable) our parent, subsidiaries, affiliates, officers, directors, agents, and employees, harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your breach of these Terms, your violation of any law, or your violation of the rights of a third party, including the infringement by you of any intellectual property or other right of any person or entity.
          </p>
          <p>
            These obligations will survive any termination of the Terms.
          </p>
        </section>

        <section>
          <h2>17. Limitation of Liability</h2>
          <p>
            Rishipath shall not be liable for any special, direct, indirect, punitive, incidental, or consequential damages, including but not limited to damages for loss of profits, business interruption, or loss of information. This applies regardless of the legal theory under which such damages are claimed, including contract, negligence, tort, or equity.
          </p>
          <p><strong>Rishipath shall not be liable for any damages arising from:</strong></p>
          <ul>
            <li>The use or inability to use the Sites or Services</li>
            <li>Defects in goods, samples, data, information, or services purchased or obtained through the Sites or Services</li>
            <li>Violations of Third Party Rights or claims related to the manufacture, importation, exportation, distribution, offer, display, purchase, sale, and/or use of products or services on the Sites or through the Services</li>
            <li>Unauthorized access by third parties to data or private information of any User</li>
            <li>Statements or conduct of any User on the Sites or Services</li>
            <li>Any other matters relating to the Sites or Services, including negligence</li>
          </ul>
          <p>
            You acknowledge and agree that Rishipath functions as an online marketplace and wellness platform. We do not control or become a party to any transactions on the platform or through any affiliated payment gateways provided by independent service providers.
          </p>
          <p>
            The sale of products through the platform is a bipartite agreement between you and Rishipath. Payment transactions are processed through authorized payment service providers. Rishipath is a platform facilitating interactions and holds no liability for payment processing issues beyond our direct control.
          </p>
          <p>
            <strong>Medical Disclaimer:</strong> The information provided on this platform regarding Ayurvedic products, remedies, and treatments is for educational purposes only and is not intended to diagnose, treat, cure, or prevent any disease. Always consult with a qualified healthcare professional before starting any new health regimen.
          </p>
        </section>

        <section>
          <h2>18. Force Majeure</h2>
          <p>
            In no event shall Rishipath or any User have liability or be deemed to be in breach hereof for any failure or delay of performance resulting from any governmental action, fire, flood, insurrection, earthquake, power failure, network failure, riot, explosion, embargo, strikes (whether legal or illegal), terrorist act, labor or material shortage, transportation interruption of any kind or work slowdown or any other condition not reasonably within our control. Your payment obligations shall continue during any event of force majeure.
          </p>
        </section>

        <section>
          <h2>19. Governing Law and Jurisdiction</h2>
          <p>
            These Terms will be governed by and construed in accordance with the laws of India. Any disputes arising out of or relating to these Terms or your use of the Platform shall be subject to the exclusive jurisdiction of the courts located in India.
          </p>
        </section>

        <section>
          <h2>20. Dispute Resolution</h2>
          <p>
            Any dispute whatsoever arising between or among the Parties regarding this Agreement shall be resolved through amicable resolution between the relevant Parties upon receipt of notice for amicable resolution by any Party.
          </p>
          <p>
            If the Parties are unable to resolve any such dispute within fifteen (15) days of receipt of the notice for amicable resolution, any Party may give to the other Party a written notice of Mediation. The Parties shall appoint a Mediator who holds expertise in the relevant technical field.
          </p>
          <p>
            Provided, no resolution to the dispute can be reached through such mediation within thirty (30) working days, such dispute shall be submitted exclusively to the jurisdiction of the appropriate Courts in India.
          </p>
        </section>

        <section>
          <h2>21. Severability</h2>
          <p>
            If any provision of these Terms and Conditions is found to be invalid, unlawful, or unenforceable to any extent, such provision shall be enforced to the maximum extent permissible so as to give effect to the intent of the parties, and the remainder of these Terms and Conditions shall continue in full force and effect. The invalid, unlawful, or unenforceable provision shall be deemed severed from these Terms and Conditions and shall not affect the validity and enforceability of the remaining provisions.
          </p>
        </section>

        <section>
          <h2>22. Notices</h2>
          <p>
            Any notice, letter, document, or any other form of communication hereunder from either party shall be in writing and shall be effectively given if sent by email.
          </p>
          <p>
            <strong>Contact Information for Rishipath:</strong><br>
            Email: <strong>{{ brand.email }}</strong><br>
            Website: <strong>www.rishipath.com</strong>
          </p>
          <p>
            The contact address and email to be used by the User shall be the registered Email ID that has been used to register the account on the Platform.
          </p>
          <p>
            Any Party hereto mentioned above may change any particulars of its address via notification to the other in the manner aforesaid. The receipt of the information, communication, or notices shall be deemed to be the successful transmission of such information, communications, or notices to the concerned e-mail address as given above.
          </p>
        </section>

        <section>
          <h2>23. Miscellaneous</h2>
          <p>
            If for any reason a court of competent jurisdiction finds any provision or portion of the Terms to be unenforceable, the remainder of the Terms will continue in full force and effect. These Terms constitute the entire agreement between us and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding the subject matter of these Terms.
          </p>
          <p>
            Any waiver of any provision of the Terms will be effective only if in writing and signed by you and Rishipath. Rishipath reserves the right to investigate complaints or reported violations of these Terms and to take any action we deem necessary and appropriate. Such action may include reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties.
          </p>
          <p>
            In addition, we may take action to disclose any information necessary or appropriate to such persons or entities relating to user profiles, e-mail addresses, usage history, posted materials, IP addresses and traffic information. Rishipath reserves the right to seek all remedies available at law and in equity for violations of these Terms.
          </p>
        </section>

        <section>
          <h2>24. Contact Us</h2>
          <p>
            For questions, concerns, or complaints about these Terms of Service, or any other matters related to our Platform, please contact us at:
          </p>
          <p>
            <strong>Email:</strong> {{ brand.email }}<br>
            <strong>Website:</strong> www.rishipath.com
          </p>
          <p>
            We are committed to resolving any concerns you may have and will respond to your inquiries in a timely manner.
          </p>
        </section>

        <div class="acknowledgement">
          <p><strong>By using our Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.</strong></p>
        </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import PageHero from '@/components/PageHero.vue';

const { page: cmsPage, pending, formatDate } = await useCMSPage('terms-of-service');
const brand = useBrand();

definePageMeta({
  layout: 'default',
})

useHead({
  title: `Terms of Service - ${brand.fullName}`,
  meta: [
    { name: 'description', content: `Terms of Service for ${brand.fullName}` }
  ]
})
</script>

<style scoped lang="scss">
.legal-page {
  min-height: 100vh;
  padding: 4rem 0;
  background: $background-light;
}

.container {
  max-width: 900px;
  margin: 0 auto;
  padding: 0 1rem;
}

.legal-content {
  background: white;
  padding: 3rem;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);

  h1 {
    color: $color-primary;
    font-size: 2.5rem;
    margin-bottom: 1rem;
  }

  .last-updated {
    color: var(--text-muted);
    font-size: 0.9rem;
    margin-bottom: 2rem;
    font-style: italic;
  }

  .important-notice {
    background: #fff3cd;
    border-left: 4px solid #ffc107;
    padding: 1.5rem;
    margin-bottom: 2rem;
    border-radius: 4px;

    p {
      margin-bottom: 0.75rem;
      color: #856404;
      line-height: 1.6;

      &:last-child {
        margin-bottom: 0;
      }
    }

    strong {
      font-weight: 600;
    }
  }

  .acknowledgement {
    background: #d4edda;
    border-left: 4px solid #28a745;
    padding: 1.5rem;
    margin-top: 2rem;
    border-radius: 4px;

    p {
      margin: 0;
      color: #155724;
      font-size: 1.05rem;
      line-height: 1.6;
    }

    strong {
      font-weight: 600;
    }
  }

  section {
    margin-bottom: 2.5rem;

    h2 {
      color: $color-primary;
      font-size: 1.5rem;
      margin-bottom: 1rem;
      padding-top: 1rem;
      border-top: 1px solid rgba($color-primary, 0.1);
    }

    p {
      line-height: 1.8;
      color: var(--text-dark);
      margin-bottom: 1rem;
    }

    ul {
      margin-left: 1.5rem;
      line-height: 1.8;
      
      li {
        margin-bottom: 0.5rem;
      color: var(--text-dark);
      }
    }
  }
}

@media (max-width: 768px) {
  .legal-page {
    padding: 2rem 0;
  }

  .legal-content {
    padding: 1.5rem;

    h1 {
      font-size: 2rem;
    }

    section h2 {
      font-size: 1.25rem;
    }
  }
}

.cms-content {
  max-width: 900px;
  margin: 0 auto;
  background: white;
  padding: 3rem;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);

  :deep(h1), :deep(h2), :deep(h3) {
    color: var(--text-primary);
    margin-top: 2rem;
    margin-bottom: 1rem;
  }

  :deep(h2) {
    color: $color-primary;
    font-size: 1.5rem;
  }

  :deep(p) {
    line-height: 1.8;
    color: var(--text-dark);
    margin-bottom: 1rem;
  }

  :deep(ul), :deep(ol) {
    margin-left: 1.5rem;
    margin-bottom: 1.5rem;
    
    li {
      margin-bottom: 0.5rem;
      line-height: 1.6;
    }
  }

  @media (max-width: 768px) {
    padding: 1.5rem;
  }
}

.spinner-border {
  width: 3rem;
  height: 3rem;
  border-width: 0.3em;
}
</style>
